In [1]:
import pandas as pd

# Table and Dataframe

In [2]:
GS = pd.read_csv("Grocery_Stores_-_2013.csv")
GS.head()

,STORE NAME,LICENSE ID,ACCOUNT NUMBER,SQUARE FEET,BUFFER SIZE,ADDRESS,ZIP CODE,COMMUNITY AREA NAME,COMMUNITY AREA,WARD,CENSUS TRACT,CENSUS BLOCK,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
0,200 LIQUORS,48663.0,17055.0,5000.0,B,204 E 47TH ST,60653,GRAND BOULEVARD,38,3,17031381500,1.703138e+14,1.178462e+06,1.873949e+06,41.809424,-87.620952,"(41.8094238941, -87.6209518020)"
1,3600 COMMISSARY,24279.0,9830.0,3800.0,B,3600 N LAKE SHORE DR,60613,LAKE VIEW,6,46,17031060900,1.703106e+14,1.171866e+06,1.924645e+06,41.948684,-87.643650,"(41.9486836744, -87.6436497585)"
2,4343 PETES FRESH MARKET,1336669.0,260303.0,57000.0,A,4343 S PULASKI RD,60632,ARCHER HEIGHTS,57,14,17031570100,1.703157e+14,1.150448e+06,1.875370e+06,41.813914,-87.723665,"(41.8139143113, -87.7236649419)"
3,4700 PETE'S FRESH MARKET,1243125.0,245519.0,45000.0,A,4700 S KEDZIE AVE,60632,BRIGHTON PARK,58,14,17031842800,1.703184e+14,1.155792e+06,1.873271e+06,41.808047,-87.704119,"(41.8080472717, -87.7041188223)"
4,5659 W. DIVERSEY,1575023.0,277375.0,4000.0,B,5659 W DIVERSEY AVE,60639,BELMONT CRAGIN,19,30,17031190602,1.703119e+14,1.137914e+06,1.918002e+06,41.931135,-87.768612,"(41.9311354035, -87.7686121306)"

In [9]:
# GS.size # 8602
Store_name = GS["STORE NAME"]
print("Name of the stores:", Store_name)

Name of the stores: 0                                200 LIQUORS
1                            3600 COMMISSARY
2                    4343 PETES FRESH MARKET
3                   4700 PETE'S FRESH MARKET
4                           5659 W. DIVERSEY
5      7400 S HALSTED FOOD AND LIQUORS, INC.
6                             79 FOOD BASKET
7                      A & B FOOD MARKET INC
8                              A & G LIQUORS
9                            A & R FOOD MART
10                           A & R FOOD MART
11                             AARAY GROCERY
12                                 ADA FOODS
13                           ADAMS FOOD MART
14                     AL BAYAN GROCERY INC.
15                                      ALDI
16                                      ALDI
17                                  ALDI #28
18                                  ALDI #30
19                                  ALDI #32
20                                  ALDI #70
21                                  ALDI #79
22                            ALDI FOODS #91
23                     ALDI FOODS -STORE #04
24                       ALDI FOODS STORE #2
25                      ALDI FOODS STORE #26
26                      ALDI FOODS STORE #30
27                     ALDI FOODS STORE #90B
28                      ALDI FOODS-STORE #27
29                             ALDI INC # 62
                       ...
476              WAY LOW DISCOUNT FOOD, INC.
477                WEST HAVEN MARKET & GRILL
478                          WEST LAWN FOODS
479                       WHOLE FOODS MARKET
480                       WHOLE FOODS MARKET
481                       WHOLE FOODS MARKET
482                       WHOLE FOODS MARKET
483                       WHOLE FOODS MARKET
484                       WHOLE FOODS MARKET
485                        WILLIAM'S PRODUCE
486                           WINDY CITY INC
487                       WORLD FRESH MARKET
488                      Z & S FOOD & LIQUOR
489                      ZEE DOLLAR AND FOOD
490                     ZIAD CERTIFIED FOODS
491                        WALGREENS # 05192
492                           WALGREENS #232
493                           WALGREENS #162
494                          WALGREENS #2073
495                          WALGREENS #2923
496                         WALGREENS #11410
497                           WALGREENS #226
498                                  WALMART
499                 PETE'S FRESH SUPERMARKET
500                         SAVE-A-LOT # 866
501             MARIANO'S FRESH MARKET #8507
502                        WALGREENS # 06297
503                         WALGREENS #05034
504                                  WALMART
505                         LOUIS' GROCERIES
Name: STORE NAME, Length: 506, dtype: object

In [10]:
highest_ACCOUNT_NUMBER = max(GS["ACCOUNT NUMBER"])
highest_ACCOUNT_NUMBER

372246.0

In [13]:
AN_sorted_GS = GS.sort_values('ACCOUNT NUMBER')
AN_sorted_GS.head()

,STORE NAME,LICENSE ID,ACCOUNT NUMBER,SQUARE FEET,BUFFER SIZE,ADDRESS,ZIP CODE,COMMUNITY AREA NAME,COMMUNITY AREA,WARD,CENSUS TRACT,CENSUS BLOCK,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
361,POTASH BROS. SUPERMARKET,164.0,21.0,12000.0,A,1525 N CLARK ST,60610,NEAR NORTH SIDE,8,42,17031080201,1.703108e+14,1.175288e+06,1.910618e+06,41.910118,-87.631491,"(41.9101179449, -87.6314908914)"
215,JERUSALEM LIQUORS,440.0,80.0,4500.0,B,3133 W LAWRENCE AVE,60625,ALBANY PARK,14,33,17031140800,1.703114e+14,1.154473e+06,1.931680e+06,41.968355,-87.707394,"(41.9683547002, -87.7073943249)"
276,"LA UNICA FOOD MART, INC.",491.0,90.0,5000.0,B,1515 W DEVON AVE,60660,EDGEWATER,77,40,17031030200,1.703103e+14,1.164986e+06,1.942560e+06,41.997993,-87.668428,"(41.9979934597, -87.6684278857)"
491,WALGREENS # 05192,1144217.0,147.0,NaN,A,2924 E 92ND ST,60617,SOUTH CHICAGO,46,7,17031461000,1.703150e+14,1.197293e+06,1.844563e+06,41.728337,-87.552860,"(41.72833654, -87.55286024)"
493,WALGREENS #162,18419.0,147.0,NaN,A,1554 E 55TH ST,60615,HYDE PARK,41,4,17031410800,1.703140e+14,1.187538e+06,1.868878e+06,41.795297,-87.587823,"(41.79529732, -87.58782256)"

In [15]:
AN_sorted_GS = GS.sort_values('ACCOUNT NUMBER', ascending=False)
AN_sorted_GS.head()

,STORE NAME,LICENSE ID,ACCOUNT NUMBER,SQUARE FEET,BUFFER SIZE,ADDRESS,ZIP CODE,COMMUNITY AREA NAME,COMMUNITY AREA,WARD,CENSUS TRACT,CENSUS BLOCK,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
505,LOUIS' GROCERIES,2153429.0,372246.0,NaN,A,7604 S COTTAGE GROVE AVE,60619,GREATER GRAND CROSSING,69,6,17031691400,1.703170e+14,1.182842e+06,1.854718e+06,41.756550,-87.605483,"(41.75655031, -87.60548285)"
501,MARIANO'S FRESH MARKET #8507,2163771.0,360006.0,NaN,A,5353 N ELSTON AVE,60630,JEFFERSON PARK,11,45,17031110100,1.703110e+14,1.140915e+06,1.935359e+06,41.978710,-87.757154,"(41.97871026, -87.75715377)"
485,WILLIAM'S PRODUCE,2079521.0,359604.0,6375.0,B,6309 W GRAND AVE,60639,BELMONT CRAGIN,19,29,17031191301,1.703119e+14,1.133912e+06,1.914608e+06,41.921894,-87.783398,"(41.9218942299, -87.7833975200)"
82,CARNICERIA GUANAJUATO,2069477.0,358374.0,9325.0,B,5250 W FULLERTON AVE,60639,BELMONT CRAGIN,19,31,17031190702,1.703119e+14,1.140756e+06,1.915489e+06,41.924189,-87.758230,"(41.9241891458, -87.7582297412)"
109,Chicago Health - Maple Street,2065274.0,357879.0,2900.0,B,22 W MAPLE ST,60610,NEAR NORTH SIDE,8,42,17031081100,1.703108e+14,1.175919e+06,1.907659e+06,41.901983,-87.629263,"(41.9019825524, -87.6292631031)"

In [24]:
name_of_biggest_AN = AN_sorted_GS["STORE NAME"]
name_of_biggest_AN = name_of_biggest_AN.reset_index(drop=True)
name_of_biggest_AN[0]

"LOUIS' GROCERIES"

In [25]:
zip_code_60639 = GS[GS["ZIP CODE"] == 60639]
zip_code_60639.head()

,STORE NAME,LICENSE ID,ACCOUNT NUMBER,SQUARE FEET,BUFFER SIZE,ADDRESS,ZIP CODE,COMMUNITY AREA NAME,COMMUNITY AREA,WARD,CENSUS TRACT,CENSUS BLOCK,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
4,5659 W. DIVERSEY,1575023.0,277375.0,4000.0,B,5659 W DIVERSEY AVE,60639,BELMONT CRAGIN,19,30,17031190602,1.703119e+14,1.137914e+06,1.918002e+06,41.931135,-87.768612,"(41.9311354035, -87.7686121306)"
9,A & R FOOD MART,9125.0,4227.0,2500.0,B,5952 W GRAND AVE,60639,BELMONT CRAGIN,19,37,17031191302,1.703119e+14,1.136148e+06,1.914150e+06,41.920596,-87.775193,"(41.9205964582, -87.7751926809)"
10,A & R FOOD MART,1954411.0,340750.0,3500.0,B,5952 W GRAND AVE,60639,BELMONT CRAGIN,19,37,17031191302,1.703119e+14,1.136148e+06,1.914150e+06,41.920596,-87.775193,"(41.9205964582, -87.7751926809)"
24,ALDI FOODS STORE #2,14004.0,5273.0,15600.0,A,4645 W DIVERSEY AVE,60639,HERMOSA,20,31,17031190900,1.703119e+14,1.144687e+06,1.918166e+06,41.931461,-87.743717,"(41.9314609382, -87.7437173070)"
26,ALDI FOODS STORE #30,14000.0,5273.0,14860.0,A,4030 W WRIGHTWOOD AVE,60639,LOGAN SQUARE,22,31,17031220702,1.703122e+14,1.148929e+06,1.917010e+06,41.928208,-87.728159,"(41.9282078544, -87.7281585580)"

In [27]:
mean_squaer_feet = GS["SQUARE FEET"].mean()
mean_squaer_feet

12198.146639511202

In [31]:
large_stores = GS[GS["SQUARE FEET"] >= 13000]
large_stores.head()

,STORE NAME,LICENSE ID,ACCOUNT NUMBER,SQUARE FEET,BUFFER SIZE,ADDRESS,ZIP CODE,COMMUNITY AREA NAME,COMMUNITY AREA,WARD,CENSUS TRACT,CENSUS BLOCK,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
2,4343 PETES FRESH MARKET,1336669.0,260303.0,57000.0,A,4343 S PULASKI RD,60632,ARCHER HEIGHTS,57,14,17031570100,1.703157e+14,1.150448e+06,1.875370e+06,41.813914,-87.723665,"(41.8139143113, -87.7236649419)"
3,4700 PETE'S FRESH MARKET,1243125.0,245519.0,45000.0,A,4700 S KEDZIE AVE,60632,BRIGHTON PARK,58,14,17031842800,1.703184e+14,1.155792e+06,1.873271e+06,41.808047,-87.704119,"(41.8080472717, -87.7041188223)"
15,ALDI,1959623.0,5273.0,15680.0,A,6221 N BROADWAY,60660,EDGEWATER,77,49,17031030103,1.703103e+14,1.167209e+06,1.941564e+06,41.995211,-87.660278,"(41.9952114602, -87.6602779929)"
16,ALDI,1922075.0,5273.0,16615.0,A,6621 S COTTAGE GROVE AVE,60637,WOODLAWN,42,5,17031420800,1.703142e+14,1.182742e+06,1.861188e+06,41.774306,-87.605648,"(41.7743058812, -87.6056480253)"
17,ALDI #28,1519765.0,5273.0,15154.0,A,4934 S KEDZIE AVE,60632,BRIGHTON PARK,58,14,17031630300,1.703163e+14,1.155840e+06,1.871594e+06,41.803446,-87.703986,"(41.8034457131, -87.7039862718)"

In [34]:
# GS["WARD"]

In [35]:
large_WARD_stores = GS[GS["WARD"] >= 25]
large_WARD_stores_size = large_WARD_stores["SQUARE FEET"].mean()
small_WARD_stores = GS[GS["WARD"] < 25]
small_WARD_stores_size = small_WARD_stores["SQUARE FEET"].mean()

print("Average store size of large WARD stores:", large_WARD_stores_size)
print("Average store size of small WARD stores:", small_WARD_stores_size)

Average store size of large WARD stores: 12183.323741
Average store size of small WARD stores: 12217.4929577

In [36]:
proportion_in_large_WARD_stores = large_WARD_stores.size/GS.size
proportion_in_small_WARD_stores = small_WARD_stores.size/GS.size

print("Proportion in large WARD stores:", proportion_in_large_WARD_stores)
print("Proportion in small WARD stores:", proportion_in_small_WARD_stores)

Proportion in large WARD stores: 0.555335968379
Proportion in small WARD stores: 0.444664031621

In [37]:
even_WARD_stores = GS[GS["WARD"]%2 == 0]
num_even_WARD_stores = even_WARD_stores.size
num_even_WARD_stores

4675

In [38]:
# Grocery Stores which is just above 13000 square feet
GS_over_13000 = large_stores.sort_values('SQUARE FEET', ascending=False)
GS_just_over_13000 = GS_over_13000["STORE NAME"]
GS_just_over_13000 = GS_just_over_13000.reset_index(drop=True)
GS_just_over_13000[0]

'SAVE-A-LOT  #851'

In [40]:
GS_location = GS[['STORE NAME', 'X COORDINATE', 'Y COORDINATE', 'LATITUDE', 'LONGITUDE', 'LOCATION']]
GS_location.head()

,STORE NAME,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
0,200 LIQUORS,1.178462e+06,1.873949e+06,41.809424,-87.620952,"(41.8094238941, -87.6209518020)"
1,3600 COMMISSARY,1.171866e+06,1.924645e+06,41.948684,-87.643650,"(41.9486836744, -87.6436497585)"
2,4343 PETES FRESH MARKET,1.150448e+06,1.875370e+06,41.813914,-87.723665,"(41.8139143113, -87.7236649419)"
3,4700 PETE'S FRESH MARKET,1.155792e+06,1.873271e+06,41.808047,-87.704119,"(41.8080472717, -87.7041188223)"
4,5659 W. DIVERSEY,1.137914e+06,1.918002e+06,41.931135,-87.768612,"(41.9311354035, -87.7686121306)"

In [41]:
average_latitude = GS_location["Y COORDINATE"].mean()
average_longitude = GS_location["X COORDINATE"].mean()
print("The average of US grocery stores' coordinates is located at (", average_latitude, ",", average_longitude, ")")

The average of US grocery stores' coordinates is located at ( 1892832.05 , 1161720.26654 )

In [44]:
GS_without_BUFFER_SIZE = GS.drop("BUFFER SIZE", axis=1)
GS_without_BUFFER_SIZE.head()

,STORE NAME,LICENSE ID,ACCOUNT NUMBER,SQUARE FEET,ADDRESS,ZIP CODE,COMMUNITY AREA NAME,COMMUNITY AREA,WARD,CENSUS TRACT,CENSUS BLOCK,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
0,200 LIQUORS,48663.0,17055.0,5000.0,204 E 47TH ST,60653,GRAND BOULEVARD,38,3,17031381500,1.703138e+14,1.178462e+06,1.873949e+06,41.809424,-87.620952,"(41.8094238941, -87.6209518020)"
1,3600 COMMISSARY,24279.0,9830.0,3800.0,3600 N LAKE SHORE DR,60613,LAKE VIEW,6,46,17031060900,1.703106e+14,1.171866e+06,1.924645e+06,41.948684,-87.643650,"(41.9486836744, -87.6436497585)"
2,4343 PETES FRESH MARKET,1336669.0,260303.0,57000.0,4343 S PULASKI RD,60632,ARCHER HEIGHTS,57,14,17031570100,1.703157e+14,1.150448e+06,1.875370e+06,41.813914,-87.723665,"(41.8139143113, -87.7236649419)"
3,4700 PETE'S FRESH MARKET,1243125.0,245519.0,45000.0,4700 S KEDZIE AVE,60632,BRIGHTON PARK,58,14,17031842800,1.703184e+14,1.155792e+06,1.873271e+06,41.808047,-87.704119,"(41.8080472717, -87.7041188223)"
4,5659 W. DIVERSEY,1575023.0,277375.0,4000.0,5659 W DIVERSEY AVE,60639,BELMONT CRAGIN,19,30,17031190602,1.703119e+14,1.137914e+06,1.918002e+06,41.931135,-87.768612,"(41.9311354035, -87.7686121306)"

In [46]:
GS_NS_sorted = GS.sort_values("Y COORDINATE", ascending=False)
northern_GS = GS_NS_sorted.head(5)
northern_GS

,STORE NAME,LICENSE ID,ACCOUNT NUMBER,SQUARE FEET,BUFFER SIZE,ADDRESS,ZIP CODE,COMMUNITY AREA NAME,COMMUNITY AREA,WARD,CENSUS TRACT,CENSUS BLOCK,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
349,PAULINA SUPER MARKET INC,4851.0,3286.0,7000.0,B,7622 N PAULINA ST,60626,ROGERS PARK,1,49,17031010100,1.703101e+14,1.163617e+06,1.950602e+06,42.020087,-87.673235,"(42.0200873150, -87.6732345632)"
443,THE FISH KEG INC,4908.0,3299.0,4000.0,B,2233 W HOWARD ST,60645,WEST RIDGE,2,49,17031020100,1.703102e+14,1.160145e+06,1.950323e+06,42.019395,-87.686020,"(42.0193947424, -87.6860204976)"
140,DOMINICK'S #160/1698,41689.0,5033.0,72000.0,A,1763 W HOWARD ST,60626,ROGERS PARK,1,49,17031010202,1.703101e+14,1.163124e+06,1.950307e+06,42.019289,-87.675059,"(42.0192885501, -87.6750585094)"
59,AROUND THE CLOCK,15860.0,6777.0,3000.0,B,1605 W HOWARD ST,60626,ROGERS PARK,1,49,17031010202,1.703101e+14,1.164071e+06,1.950305e+06,42.019265,-87.671572,"(42.0192651821, -87.6715720734)"
151,EDDY'S FOOD MART,1879269.0,324962.0,4000.0,B,7575 N ROGERS AVE,60626,ROGERS PARK,1,49,17031010300,1.703101e+14,1.164934e+06,1.950275e+06,42.019165,-87.668397,"(42.0191646250, -87.6683972880)"

In [48]:
buffer_A_GS = GS[GS["BUFFER SIZE"] == 'A']
buffer_A_GS.head()

,STORE NAME,LICENSE ID,ACCOUNT NUMBER,SQUARE FEET,BUFFER SIZE,ADDRESS,ZIP CODE,COMMUNITY AREA NAME,COMMUNITY AREA,WARD,CENSUS TRACT,CENSUS BLOCK,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
2,4343 PETES FRESH MARKET,1336669.0,260303.0,57000.0,A,4343 S PULASKI RD,60632,ARCHER HEIGHTS,57,14,17031570100,1.703157e+14,1.150448e+06,1.875370e+06,41.813914,-87.723665,"(41.8139143113, -87.7236649419)"
3,4700 PETE'S FRESH MARKET,1243125.0,245519.0,45000.0,A,4700 S KEDZIE AVE,60632,BRIGHTON PARK,58,14,17031842800,1.703184e+14,1.155792e+06,1.873271e+06,41.808047,-87.704119,"(41.8080472717, -87.7041188223)"
5,"7400 S HALSTED FOOD AND LIQUORS, INC.",980.0,186.0,10001.0,A,7400 S HALSTED ST,60621,ENGLEWOOD,68,17,17031681300,1.703168e+14,1.172209e+06,1.855769e+06,41.759675,-87.644420,"(41.7596745819, -87.6444202389)"
7,A & B FOOD MARKET INC,43181.0,6483.0,10001.0,A,5057 W DIVISION ST,60651,AUSTIN,25,37,17031251100,1.703125e+14,1.142184e+06,1.907473e+06,41.902166,-87.753182,"(41.9021664421, -87.7531823487)"
11,AARAY GROCERY,1900.0,62541.0,10001.0,A,2601 N HALSTED ST,60614,LINCOLN PARK,7,43,17031070200,1.703107e+14,1.170536e+06,1.917538e+06,41.929210,-87.648746,"(41.9292098170, -87.6487462650)"